# 为MinGW设置的交叉编译工具链文件

# 系统名称
set(CMAKE_SYSTEM_NAME Windows)

# 指定C编译器
set(CMAKE_C_COMPILER "gcc")

# 指定C++编译器
set(CMAKE_CXX_COMPILER "g++")

# 设置查找程序、库和包时的根路径
set(CMAKE_FIND_ROOT_PATH /mingw64)

# 调整查找行为，让CMake只在目标环境中查找
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# 静态链接设置
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static")
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")
set(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS "")

# 禁用RPATH
set(CMAKE_SKIP_RPATH ON)
